### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by dopelsunce** [o2lab/go2#1]
Investigate and fix the failling tests commented out in TestRace (race_test.go):

- [x] "tests/waitgroup.go",
- [x] "tests/lock.go",
- [x] "tests/k8s_issue80269.go",
- [x] "tests/map_race.go",
- [x] "tests/select.go",
- [x] "tests/race_cfg.go",

**Comment by LornaLou** [comment]
k8s_issue80269.go is having a false negative, because currently we have a mistaken happens before connecting the instructions after the select ends to the instructions inside the case.
