### ISSUE TITLE
Separate test entry points from main() entry points

### ISSUE THREAD

**Issue by zyq823** [o2lab/go2#15]
Separate test entry points from main() entry points. 
-analyzeAll  would pertain to analyzing all main() entry points. 

OR

make -analyzeAll execute all main() entry points along with all test entry points (** consider overlapping coverage)

**Comment by april1989** [comment]
The structure of a test is like this: 
```
xx/xx/xx.test 
|___ TestA 
|___ TestB 
|___ TestC
|___ ExampleA 
|___ ExampleB
|___ ExampleC 
|___ BenchmarkA
```
use each ```TestX``` and ```ExampleX``` and ```Benchmark``` as entry point (returned by pta) to run visitAllInstruction and buildHB. 

NOTE: create a separate function to handle these kind of tests if user has one or multiple selection or -analyzeAll.
